language: ruby
rvm:
- 1.9.3
services:
- mongodb
env:
  global:
  - secure: KMTBHE7IhmTeVuEdWwV5L9ghZXV8PVhJvatE+YZhJ7qKEM42sJNG3sy6A4uS9Kuq7OTa/J38u9NkJDfo4CY8cxOz+coqrqpiw/LRSMkmSrPaDcnK6hcv9LhNY6BmnfPPgStXmc52cboxLsPtBhdJ3UmeHiWVpCTz6fKYo/Aksnc=
  - secure: gUxvj+DejoDU65zTggftrnu1uXCen8088UbMblzixmeH1+B+CK7s/307hy8M7cuX6HDRMMDE1aARFhK3idZOsWVMJcoH6F6JH/Dp60/VVTldnR74SfT+H1IV4zW1E0IAv45/bgGWvPKzGlkxYy7uf49mjNNLxmaScjZW8YKz91w=
  - SMTP_PORT=3535
  - SMTP_HOST=smtpout.secureserver.net
  - secure: bq9mn45ScBPYeb0oT2VGvSX7Sa1Byfp1rul0DArBo3OHTB6wpIl4+XpDNeGAeXMUPDWN56X7FHvOEHjn8ZSXt6H4LjdX8EXim58JmOxMRLT/nxm1ZGGoUAFISyxKzMZxh7ff0HIYWK1nOFQLO5VS9zreo+jbBYnYkV8B5Eqda3g=
  - secure: AhAvHbc+nbDCTNVS68jbCtx370KGY9KD63CQf6ibZpr/S2uz+RhUeO7al/e0gPl1kYDKc86x//dnvhdt22XDtSVu0Q70kJ7IYeBAkHnbETVin0f1YcXH52W7N9SGxXm01SamMQ2ghw/dDqk2nOkQ9wXm+MwK9whnfHCh90FoU+s=
  - secure: ASU0rHOwuIUEZ7pVSc+Ezl1mh3EbwAt+LINan5m7fk+XSXBP0lM7WKjt6fTCoru1dQ1UOljlHE2LFAGVuDMj022HN2mjsWzNqyDnkYOEkUCbhBFKTBlSrgQI+c9uI19H2MNpoZwyrEog2RTad47Va8ofzauS2QFQPRvENvEsg7g=
  - CONTACT_EMAILBOX='operations@example.com'
  - CONTACT_FROM='no-reply-mailbox@example.com'
  - CONTACT_SUBJECT='New Contact Request'
  - GROUP_FROM_EMAIL="no-reply-mailbox@example.com"
  - GROUP_EMAIL_SUBJECT="Group Membership Notification"
  - secure: E9mwJ4E95deUbMjm62uRfyHbM/uaCszKVsIKSnJqX3Z9KlOYKVKz3avfRi6vE7NxZTPTuTTUD167u3ILONQzg8a1szjaxF7VlMJesKcTom8REU89PgIcGIrDJMDicZ3ecxEeULffFENgKBNAsanSHLDPX4XkzNKn4+c0irQNCjg=
  - secure: NiIBM5qDLPftSemhcUk6anZ6Ssj6NIZYia+7CY5SmqvL0q4b97arzOf8HX4TxhDRyNYtOKppg8St+tf2GRK6tDBD0VM2Ow8wP38gJEiGV/400qFZjiqkwyNaoK0TGLEmnykOp5+dsbTpJ4C+WxMWv2QWXMDNTjwoDQDUhLMLsqY=
  - secure: Dpa0Khg2F24Ck/7KaP4Lxk42O+SDVhPtqID03XEDvbTRuyjltoWTEhLbb9ovtCgZX6LbsWStlsDlTGbrG720bP2SagnV0OHvUn+fxl/I6hbyjcn4r4bPcmfbEzv9Hl9CjUcbr8GOAmbNPjL2kTZD4RORKKSUcj0pajO0StzkaP4=
branches:
  only:
  - master
  - development
deploy:
  provider: openshift
  user: alim@nspartners.com
  password:
    secure: Z9wEVbG5Iy2F5p3WrUU7mk1OWhLw7KGT4lHttuYum0U7bn0SfGVdrohgojTvDLSzm2g6HJK0WgoZMXhAoMFTGDUg6HnHexTFRsEALm45La2aThgrd4nHCcr/LlSX4NdJLIBGJB7Hv1SDqGRGMYpdqcU7Gm/RYCkSGeALHhCzBJM=
  app: aronoff
  domain: nspartners
  on:
    repo: alim/aronoff
