language: ruby
rvm:
- 1.9.3
services:
- mongodb
env:
  global:
  - secure: KMTBHE7IhmTeVuEdWwV5L9ghZXV8PVhJvatE+YZhJ7qKEM42sJNG3sy6A4uS9Kuq7OTa/J38u9NkJDfo4CY8cxOz+coqrqpiw/LRSMkmSrPaDcnK6hcv9LhNY6BmnfPPgStXmc52cboxLsPtBhdJ3UmeHiWVpCTz6fKYo/Aksnc=
  - secure: gUxvj+DejoDU65zTggftrnu1uXCen8088UbMblzixmeH1+B+CK7s/307hy8M7cuX6HDRMMDE1aARFhK3idZOsWVMJcoH6F6JH/Dp60/VVTldnR74SfT+H1IV4zW1E0IAv45/bgGWvPKzGlkxYy7uf49mjNNLxmaScjZW8YKz91w=
  - SMTP_PORT=3535
  - SMTP_HOST=smtpout.secureserver.net
  - secure: bq9mn45ScBPYeb0oT2VGvSX7Sa1Byfp1rul0DArBo3OHTB6wpIl4+XpDNeGAeXMUPDWN56X7FHvOEHjn8ZSXt6H4LjdX8EXim58JmOxMRLT/nxm1ZGGoUAFISyxKzMZxh7ff0HIYWK1nOFQLO5VS9zreo+jbBYnYkV8B5Eqda3g=
  - secure: AhAvHbc+nbDCTNVS68jbCtx370KGY9KD63CQf6ibZpr/S2uz+RhUeO7al/e0gPl1kYDKc86x//dnvhdt22XDtSVu0Q70kJ7IYeBAkHnbETVin0f1YcXH52W7N9SGxXm01SamMQ2ghw/dDqk2nOkQ9wXm+MwK9whnfHCh90FoU+s=
  - secure: ASU0rHOwuIUEZ7pVSc+Ezl1mh3EbwAt+LINan5m7fk+XSXBP0lM7WKjt6fTCoru1dQ1UOljlHE2LFAGVuDMj022HN2mjsWzNqyDnkYOEkUCbhBFKTBlSrgQI+c9uI19H2MNpoZwyrEog2RTad47Va8ofzauS2QFQPRvENvEsg7g=
  - CONTACT_EMAILBOX='operations@example.com'
  - CONTACT_FROM='no-reply-mailbox@example.com'
  - CONTACT_SUBJECT='New Contact Request'
  - GROUP_FROM_EMAIL="no-reply-mailbox@example.com"
  - GROUP_EMAIL_SUBJECT="Group Membership Notification"
branches:
  only:
  - master
  - development
deploy:
  provider: openshift
  user: andy.nsp@gmail.com
  password:
    secure: gkSbUyKmMFc54okjWkBtwEdiCUFX5JkGdaY0SZpIt/dnfEUTGNjlSaz2PUiIGXL1iJMJUBbIsaiV180dL1PAa+xCjqt7nCH0qjmmiu8lGex6Z4fPKr98J3hVpAIfGIxo6Nghg4W7Q6UuJEqaFQtN6Z8RGYrEhOGMEE6t0NoQoCQ=
  app: aronoff
  domain: netsourcedev
  on:
    repo: alim/aronoff
