require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ImmuneResponsesController do

  # This should return the minimal set of attributes required to create a valid
  # ImmuneResponse. As you add validations to ImmuneResponse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "experiment_id" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ImmuneResponsesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all immune_responses as @immune_responses" do
      immune_response = ImmuneResponse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:immune_responses).should eq([immune_response])
    end
  end

  describe "GET show" do
    it "assigns the requested immune_response as @immune_response" do
      immune_response = ImmuneResponse.create! valid_attributes
      get :show, {:id => immune_response.to_param}, valid_session
      assigns(:immune_response).should eq(immune_response)
    end
  end

  describe "GET new" do
    it "assigns a new immune_response as @immune_response" do
      get :new, {}, valid_session
      assigns(:immune_response).should be_a_new(ImmuneResponse)
    end
  end

  describe "GET edit" do
    it "assigns the requested immune_response as @immune_response" do
      immune_response = ImmuneResponse.create! valid_attributes
      get :edit, {:id => immune_response.to_param}, valid_session
      assigns(:immune_response).should eq(immune_response)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ImmuneResponse" do
        expect {
          post :create, {:immune_response => valid_attributes}, valid_session
        }.to change(ImmuneResponse, :count).by(1)
      end

      it "assigns a newly created immune_response as @immune_response" do
        post :create, {:immune_response => valid_attributes}, valid_session
        assigns(:immune_response).should be_a(ImmuneResponse)
        assigns(:immune_response).should be_persisted
      end

      it "redirects to the created immune_response" do
        post :create, {:immune_response => valid_attributes}, valid_session
        response.should redirect_to(ImmuneResponse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved immune_response as @immune_response" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImmuneResponse.any_instance.stub(:save).and_return(false)
        post :create, {:immune_response => { "experiment_id" => "invalid value" }}, valid_session
        assigns(:immune_response).should be_a_new(ImmuneResponse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImmuneResponse.any_instance.stub(:save).and_return(false)
        post :create, {:immune_response => { "experiment_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested immune_response" do
        immune_response = ImmuneResponse.create! valid_attributes
        # Assuming there are no other immune_responses in the database, this
        # specifies that the ImmuneResponse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ImmuneResponse.any_instance.should_receive(:update).with({ "experiment_id" => "" })
        put :update, {:id => immune_response.to_param, :immune_response => { "experiment_id" => "" }}, valid_session
      end

      it "assigns the requested immune_response as @immune_response" do
        immune_response = ImmuneResponse.create! valid_attributes
        put :update, {:id => immune_response.to_param, :immune_response => valid_attributes}, valid_session
        assigns(:immune_response).should eq(immune_response)
      end

      it "redirects to the immune_response" do
        immune_response = ImmuneResponse.create! valid_attributes
        put :update, {:id => immune_response.to_param, :immune_response => valid_attributes}, valid_session
        response.should redirect_to(immune_response)
      end
    end

    describe "with invalid params" do
      it "assigns the immune_response as @immune_response" do
        immune_response = ImmuneResponse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImmuneResponse.any_instance.stub(:save).and_return(false)
        put :update, {:id => immune_response.to_param, :immune_response => { "experiment_id" => "invalid value" }}, valid_session
        assigns(:immune_response).should eq(immune_response)
      end

      it "re-renders the 'edit' template" do
        immune_response = ImmuneResponse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImmuneResponse.any_instance.stub(:save).and_return(false)
        put :update, {:id => immune_response.to_param, :immune_response => { "experiment_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested immune_response" do
      immune_response = ImmuneResponse.create! valid_attributes
      expect {
        delete :destroy, {:id => immune_response.to_param}, valid_session
      }.to change(ImmuneResponse, :count).by(-1)
    end

    it "redirects to the immune_responses list" do
      immune_response = ImmuneResponse.create! valid_attributes
      delete :destroy, {:id => immune_response.to_param}, valid_session
      response.should redirect_to(immune_responses_url)
    end
  end

end
